library(tidyverse) 
library(dplyr) 
library(janitor) 
library(here) 
library(stringr) 

data_2015 <- readxl::read_xlsx(here("raw_data/candy_ranking_data/boing-boing-candy-2015.xlsx")) 
data_2016 <- readxl::read_xlsx(here("raw_data/candy_ranking_data/boing-boing-candy-2016.xlsx")) 
data_2017 <- readxl::read_xlsx(here("raw_data/candy_ranking_data/boing-boing-candy-2017.xlsx")) 

cleaned_names_data_2015 <- clean_names(data_2015) 
cleaned_names_data_2016 <- clean_names(data_2016) 
cleaned_names_data_2017 <- clean_names(data_2017) 

country_column_tidied_up_2016 <- cleaned_names_data_2016 %>% 
  mutate(which_country_do_you_live_in = recode(which_country_do_you_live_in, 
                                              "usa" = "USA", 
                                              "us" = "USA", 
                                              "US" = "USA", 
                                              "USSA" = "USA", 
                                              "USA!!!!!!" = "USA", 
                                              "USA! USA! USA!" = "USA", 
                                              "USA! USA!" = "USA", 
                                              "USA!" = "USA", 
                                              "USA USA USA USA" = "USA", 
                                              "USA USA USA" = "USA", 
                                              "USA (I think but it's an election year so who can really tell)" 
                                              = "USA", 
                                              "Usa" = "USA", 
                                              "uSA" = "USA", 
                                              "Units States" = "USA", 
                                              "United Stetes" = "USA", 
                                              "United States of America" = "USA", 
                                              "UNited States" = "USA", 
                                              "United States" = "USA", 
                                              "United  States of America" = "USA", 
                                              "United State" = "USA", 
                                              "United Sates" = "USA", 
                                              "U.S.A." = "USA", 
                                              "U.S." = "USA", 
                                              "U.s." = "USA", 
                                              "Trumpistan" = "USA", 
                                              "Murica" = "USA", 
                                              "Merica" = "USA", 
                                              "america" = "USA", 
                                              "America" = "USA", 
                                              "The Yoo Ess of Aaayyyyyy" = "USA", 
                                              "30.0" = "USA", 
                                              "44.0" = "USA", 
                                              "45.0" = "USA", 
                                              "47.0" = "USA", 
                                              "51.0" = "USA", 
                                              "54.0" = "USA", 
                                              "the best one - usa" = "USA", 
                                              "Us" = "USA", 
                                              "united states of america" = "USA", 
                                              "United states" = "USA", 
                                              "united states" = "USA", 
                                              "u.s." = "USA", 
                                              "United Kingdom" = "UK", 
                                              "uk" = "UK", 
                                              "United Kindom" = "UK", 
                                              "netherlands" = "Netherlands", 
                                              "canada" = "Canada", 
                                              "england" = "UK", 
                                              "England" = "UK", 
                                              "france" = "France", 
                                              "germany" = "Germany"))  

country_column_tidied_up_2017 <- cleaned_names_data_2017 %>% 
  mutate(q4_country = recode(q4_country, 
    "usa" = "USA", 
    "us" = "USA", 
    "US" = "USA", 
    "USSA" = "USA", 
    "USAUSAUSA" = "USA", 
    "usas" = "USA", 
    "USAA" = "USA", 
    "USA? Hard to tell anymore.." = "USA", 
    "USA USA USA!!!!" = "USA", 
    "US of A" = "USA", 
    "U S" = "USA", 
    "u s a" = "USA", 
    "USA!!!!!!" = "USA", 
    "USA! USA! USA!" = "USA", 
    "USA! USA!" = "USA", 
    "USA!" = "USA", 
    "USA USA USA USA" = "USA", 
    "USA USA USA" = "USA", 
    "USA (I think but it's an election year so who can really tell)" 
    = "USA", 
    "Usa" = "USA", 
    "uSA" = "USA", 
    "Units States" = "USA", 
    "United Stetes" = "USA", 
    "United States of America" = "USA", 
    "UNited States" = "USA", 
    "United States" = "USA", 
    "United  States of America" = "USA", 
    "United State" = "USA", 
    "United Sates" = "USA", 
    "U.S.A." = "USA", 
    "U.S." = "USA", 
    "U.s." = "USA", 
    "Trumpistan" = "USA", 
    "Murica" = "USA", 
    "Merica" = "USA", 
    "america" = "USA", 
    "America" = "USA", 
    "The Yoo Ess of Aaayyyyyy" = "USA", 
    "murrika" = "USA", 
    "I pretend to be from Canada, but I am really from the United States." = "USA", 
    "30.0" = "USA", 
    "44.0" = "USA", 
    "45.0" = "USA", 
    "47.0" = "USA", 
    "51.0" = "USA", 
    "54.0" = "USA", 
    "the best one - usa" = "USA", 
    "Us" = "USA", 
    "united states of america" = "USA", 
    "United states" = "USA", 
    "united states" = "USA", 
    "Ahem....Amerca" = "USA", 
    "merica" = "USA", 
    "'merica" = "USA", 
    "32" = "USA", 
    "35" = "USA", 
    "45" = "USA", 
    "46" = "USA", 
    "Alaska" = "USA", 
    "u.s." = "USA", 
    "United Kingdom" = "UK", 
    "uk" = "UK", 
    "United Kindom" = "UK", 
    "netherlands" = "Netherlands", 
    "canada" = "Canada", 
    "england" = "UK", 
    "England" = "UK", 
    "france" = "France", 
    "germany" = "Germany", 
    "Scotland" = "USA", 
    "CANADA" = "Canada", 
    "Canada`" = "Canada", 
    "Can" = "Canada"))  
